export const cssColorableProperties = [
	'color',
	'background',
	'background-color',
	'background-image',
	'border',
	'border-top',
	'border-right',
	'border-bottom',
	'border-left',
	'border-color',
	'border-top-color',
	'border-right-color',
	'border-bottom-color',
	'border-left-color',
	'border-block-end',
	'border-block-end-color',
	'border-block-start',
	'border-block-start-color',
	'border-inline-end',
	'border-inline-end-color',
	'border-inline-start',
	'border-inline-start-color',
	'box-shadow',
	'caret-color',
	'column-rule',
	'column-rule-color',
	'outline',
	'outline-color',
	'text-decoration',
	'text-decoration-color',
	'text-emphasis',
	'text-emphasis-color',
	'text-shadow',

	/** SVG */
	'fill',
	'stroke',
	'stop-color',
	'flood-color',
	'lighting-color',

	/** Vendor specific */
	'-ms-scrollbar-3dlight-color',
	'-ms-scrollbar-base-color',
	'-ms-scrollbar-face-color',
	'-ms-scrollbar-shadow-color',
	'-moz-border-top-colors',
	'-moz-border-right-colors',
	'-moz-border-bottom-colors',
	'-moz-border-left-colors',
	'-webkit-border-before',
	'-webkit-tap-highlight-color',
	'-webkit-text-stroke',
	'-webkit-text-stroke-color',
];
