# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
    - next

init:
  - git config --global core.autocrlf input

cache:
  - "..\\.yarn-cache"
  - ".jest-cache"

environment:
  matrix:
    - nodejs_version: 10
      job_part: test
      jest: --maxWorkers=2 --cacheDirectory .jest-cache
    - nodejs_version: 8
      job_part: test
      jest: --maxWorkers=2 --cacheDirectory .jest-cache

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache
  - yarn link --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache || yarn link --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache
  - yarn link scancss --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - yarn --version
  - cmd: set JEST=%jest%
  - cmd: yarn appveyor:%job_part%
  - cmd: yarn unlink scancss
  - cmd: del /F /Q .jest-cache\\haste-map* .jest-cache\\perf-cache* 2> null || Ver > null
