/**
 * https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule
 * https://drafts.csswg.org/css-extensions/#custom-selectors
 * https://tabatkins.github.io/specs/css-nesting/#nesting
 */

export const cssAtRules = [
	'apply',
	'annotation',
	'bottom-center',
	'bottom-left',
	'bottom-left-corner',
	'bottom-right',
	'bottom-right-corner',
	'character-variant',
	'charset',
	'color-profile',
	'counter-style',
	'custom-media',
	'custom-selector',
	'document',
	'font-face',
	'font-feature-values',
	'import',
	'keyframes',
	'left-bottom',
	'left-middle',
	'left-top',
	'media',
	'namespace',
	'nest',
	'ornaments',
	'page',
	'right-bottom',
	'right-middle',
	'right-top',
	'styleset',
	'stylistic',
	'supports',
	'swash',
	'top-center',
	'top-left',
	'top-left-corner',
	'top-right',
	'top-right-corner',
	'viewport',
];
