export const cssAtRulesDescriptorsMap = {
	'counter-style': [
		'additive-symbols',
		'fallback',
		'negative',
		'pad',
		'prefix',
		'range',
		'speak-as',
		'suffix',
		'symbols',
		'system',
	],
	'font-face': [
		'font-display',
		'font-family',
		'font-stretch',
		'font-style',
		'font-weight',
		'font-variant',
		'font-feature-settings',
		'font-variation-settings',
		'src',
		'unicode-range',
	],
	page: [
		'size',
		'marks',
		'bleed',
	],
	viewport: [
		'min-width',
		'max-width',
		'width',
		'min-height',
		'max-height',
		'height',
		'zoom',
		'min-zoom',
		'max-zoom',
		'user-zoom',
		'orientation',
		'viewport-fit',
	],
};
